image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
stages:
    - pages

staging:
    type: deploy
    stage: staging
    image: ruby:latest
    script:
        - cd dist
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master
